site_name: Melez Zaman
site_url: 
nav:
  - Anasayfa: "index.md"
  - Melez Zaman - Kitap:
    - "Melez Zaman": "kitap/melez_zaman.md"
    - "Sıcak Para": "kitap/sicak_para.md"
    - "Kapalı Çarşı": "kitap/kapali_carsi.md"
    - "Ah Minelaşk": "kitap/ah_minelask.md"
    - "Çeşitleme": "kitap/cesitleme.md"
    - "Bir Varmış Bir Yokmuş": "kitap/bir_varmis_bir_yokmus.md"
    - "Sabahı Soruyoruz": "kitap/sabahi_soruyoruz.md"

theme: 
  name: readthedocs
  locale: tr
