site_name: Melez Zaman
site_url: 
nav:
  - Home: "index.md"
  - 'Melez Zaman':
    - "Melez Zaman": "kitap/melez-zaman.md"
    - "Sıcak Para": "kitap/sicak-para.md"
    - "Kapalı Çarşı": "kitap/kapali-carsi.md"
    - "Ah Minelaşk": "kitap/ah-minelask.md"

theme: readthedocs
